<?php
/**
 * MetaInventoryExposureApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Plainrouter\OpenAPI\ApiException;
use Plainrouter\OpenAPI\Configuration;
use Plainrouter\OpenAPI\FormDataProcessor;
use Plainrouter\OpenAPI\HeaderSelector;
use Plainrouter\OpenAPI\ObjectSerializer;

/**
 * MetaInventoryExposureApi Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MetaInventoryExposureApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getInventoryMetrics' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getInventoryMetrics
     *
     * Compare Meta metrics with counted arrivals
     *
     * @param  int $workspace The workspace ID (required)
     * @param  string $account_id account_id (required)
     * @param  \DateTime|null $start_date start_date (optional)
     * @param  \DateTime|null $end_date end_date (optional)
     * @param  string|null $campaign_id campaign_id (optional)
     * @param  string|null $adset_id adset_id (optional)
     * @param  string|null $ad_id ad_id (optional)
     * @param  bool|null $include_changes include_changes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInventoryMetrics'] to see the possible values for this operation
     *
     * @throws \Plainrouter\OpenAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Plainrouter\OpenAPI\Model\GetInventoryMetrics200Response|\Plainrouter\OpenAPI\Model\ErrorMessage|\Plainrouter\OpenAPI\Model\ErrorMessage|\Plainrouter\OpenAPI\Model\ErrorMessage|\Plainrouter\OpenAPI\Model\ValidationError
     */
    public function getInventoryMetrics($workspace, $account_id, $start_date = null, $end_date = null, $campaign_id = null, $adset_id = null, $ad_id = null, $include_changes = null, string $contentType = self::contentTypes['getInventoryMetrics'][0])
    {
        list($response) = $this->getInventoryMetricsWithHttpInfo($workspace, $account_id, $start_date, $end_date, $campaign_id, $adset_id, $ad_id, $include_changes, $contentType);
        return $response;
    }

    /**
     * Operation getInventoryMetricsWithHttpInfo
     *
     * Compare Meta metrics with counted arrivals
     *
     * @param  int $workspace The workspace ID (required)
     * @param  string $account_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string|null $campaign_id (optional)
     * @param  string|null $adset_id (optional)
     * @param  string|null $ad_id (optional)
     * @param  bool|null $include_changes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInventoryMetrics'] to see the possible values for this operation
     *
     * @throws \Plainrouter\OpenAPI\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Plainrouter\OpenAPI\Model\GetInventoryMetrics200Response|\Plainrouter\OpenAPI\Model\ErrorMessage|\Plainrouter\OpenAPI\Model\ErrorMessage|\Plainrouter\OpenAPI\Model\ErrorMessage|\Plainrouter\OpenAPI\Model\ValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getInventoryMetricsWithHttpInfo($workspace, $account_id, $start_date = null, $end_date = null, $campaign_id = null, $adset_id = null, $ad_id = null, $include_changes = null, string $contentType = self::contentTypes['getInventoryMetrics'][0])
    {
        $request = $this->getInventoryMetricsRequest($workspace, $account_id, $start_date, $end_date, $campaign_id, $adset_id, $ad_id, $include_changes, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Plainrouter\OpenAPI\Model\GetInventoryMetrics200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Plainrouter\OpenAPI\Model\ErrorMessage',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Plainrouter\OpenAPI\Model\ErrorMessage',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Plainrouter\OpenAPI\Model\ErrorMessage',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Plainrouter\OpenAPI\Model\ValidationError',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Plainrouter\OpenAPI\Model\GetInventoryMetrics200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Plainrouter\OpenAPI\Model\GetInventoryMetrics200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Plainrouter\OpenAPI\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Plainrouter\OpenAPI\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Plainrouter\OpenAPI\Model\ErrorMessage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Plainrouter\OpenAPI\Model\ValidationError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getInventoryMetricsAsync
     *
     * Compare Meta metrics with counted arrivals
     *
     * @param  int $workspace The workspace ID (required)
     * @param  string $account_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string|null $campaign_id (optional)
     * @param  string|null $adset_id (optional)
     * @param  string|null $ad_id (optional)
     * @param  bool|null $include_changes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInventoryMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInventoryMetricsAsync($workspace, $account_id, $start_date = null, $end_date = null, $campaign_id = null, $adset_id = null, $ad_id = null, $include_changes = null, string $contentType = self::contentTypes['getInventoryMetrics'][0])
    {
        return $this->getInventoryMetricsAsyncWithHttpInfo($workspace, $account_id, $start_date, $end_date, $campaign_id, $adset_id, $ad_id, $include_changes, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getInventoryMetricsAsyncWithHttpInfo
     *
     * Compare Meta metrics with counted arrivals
     *
     * @param  int $workspace The workspace ID (required)
     * @param  string $account_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string|null $campaign_id (optional)
     * @param  string|null $adset_id (optional)
     * @param  string|null $ad_id (optional)
     * @param  bool|null $include_changes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInventoryMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getInventoryMetricsAsyncWithHttpInfo($workspace, $account_id, $start_date = null, $end_date = null, $campaign_id = null, $adset_id = null, $ad_id = null, $include_changes = null, string $contentType = self::contentTypes['getInventoryMetrics'][0])
    {
        $returnType = '\Plainrouter\OpenAPI\Model\GetInventoryMetrics200Response';
        $request = $this->getInventoryMetricsRequest($workspace, $account_id, $start_date, $end_date, $campaign_id, $adset_id, $ad_id, $include_changes, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getInventoryMetrics'
     *
     * @param  int $workspace The workspace ID (required)
     * @param  string $account_id (required)
     * @param  \DateTime|null $start_date (optional)
     * @param  \DateTime|null $end_date (optional)
     * @param  string|null $campaign_id (optional)
     * @param  string|null $adset_id (optional)
     * @param  string|null $ad_id (optional)
     * @param  bool|null $include_changes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getInventoryMetrics'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getInventoryMetricsRequest($workspace, $account_id, $start_date = null, $end_date = null, $campaign_id = null, $adset_id = null, $ad_id = null, $include_changes = null, string $contentType = self::contentTypes['getInventoryMetrics'][0])
    {

        // verify the required parameter 'workspace' is set
        if ($workspace === null || (is_array($workspace) && count($workspace) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $workspace when calling getInventoryMetrics'
            );
        }

        // verify the required parameter 'account_id' is set
        if ($account_id === null || (is_array($account_id) && count($account_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $account_id when calling getInventoryMetrics'
            );
        }



        if ($campaign_id !== null && strlen($campaign_id) > 128) {
            throw new \InvalidArgumentException('invalid length for "$campaign_id" when calling MetaInventoryExposureApi.getInventoryMetrics, must be smaller than or equal to 128.');
        }

        if ($adset_id !== null && strlen($adset_id) > 128) {
            throw new \InvalidArgumentException('invalid length for "$adset_id" when calling MetaInventoryExposureApi.getInventoryMetrics, must be smaller than or equal to 128.');
        }

        if ($ad_id !== null && strlen($ad_id) > 128) {
            throw new \InvalidArgumentException('invalid length for "$ad_id" when calling MetaInventoryExposureApi.getInventoryMetrics, must be smaller than or equal to 128.');
        }



        $resourcePath = '/workspaces/{workspace}/admin/ad-accounts/{account_id}/inventory/metrics';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start_date,
            'start_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end_date,
            'end_date', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $campaign_id,
            'campaign_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $adset_id,
            'adset_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ad_id,
            'ad_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_changes,
            'include_changes', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($workspace !== null) {
            $resourcePath = str_replace(
                '{workspace}',
                ObjectSerializer::toPathValue($workspace),
                $resourcePath
            );
        }
        // path params
        if ($account_id !== null) {
            $resourcePath = str_replace(
                '{account_id}',
                ObjectSerializer::toPathValue($account_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
