<?php
/**
 * ActionBatchReadData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;

use \ArrayAccess;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * ActionBatchReadData Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ActionBatchReadData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ActionBatchRead_data';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'workspace_id' => 'int',
        'platform_ad_account_id' => 'int',
        'status' => 'string',
        'batch_status' => 'string',
        'restoration_summary' => 'string',
        'policy_decision' => 'string',
        'policy_reasons' => 'string[]',
        'rationale' => 'string',
        'idempotency_key' => 'string',
        'actions' => '\Plainrouter\OpenAPI\Model\ActionReadItem[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'workspace_id' => null,
        'platform_ad_account_id' => null,
        'status' => null,
        'batch_status' => null,
        'restoration_summary' => null,
        'policy_decision' => null,
        'policy_reasons' => null,
        'rationale' => null,
        'idempotency_key' => null,
        'actions' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'workspace_id' => false,
        'platform_ad_account_id' => false,
        'status' => false,
        'batch_status' => false,
        'restoration_summary' => true,
        'policy_decision' => true,
        'policy_reasons' => false,
        'rationale' => false,
        'idempotency_key' => false,
        'actions' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'workspace_id' => 'workspace_id',
        'platform_ad_account_id' => 'platform_ad_account_id',
        'status' => 'status',
        'batch_status' => 'batch_status',
        'restoration_summary' => 'restoration_summary',
        'policy_decision' => 'policy_decision',
        'policy_reasons' => 'policy_reasons',
        'rationale' => 'rationale',
        'idempotency_key' => 'idempotency_key',
        'actions' => 'actions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'workspace_id' => 'setWorkspaceId',
        'platform_ad_account_id' => 'setPlatformAdAccountId',
        'status' => 'setStatus',
        'batch_status' => 'setBatchStatus',
        'restoration_summary' => 'setRestorationSummary',
        'policy_decision' => 'setPolicyDecision',
        'policy_reasons' => 'setPolicyReasons',
        'rationale' => 'setRationale',
        'idempotency_key' => 'setIdempotencyKey',
        'actions' => 'setActions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'workspace_id' => 'getWorkspaceId',
        'platform_ad_account_id' => 'getPlatformAdAccountId',
        'status' => 'getStatus',
        'batch_status' => 'getBatchStatus',
        'restoration_summary' => 'getRestorationSummary',
        'policy_decision' => 'getPolicyDecision',
        'policy_reasons' => 'getPolicyReasons',
        'rationale' => 'getRationale',
        'idempotency_key' => 'getIdempotencyKey',
        'actions' => 'getActions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATUS_PENDING = 'pending';
    public const STATUS_APPROVED = 'approved';
    public const STATUS_APPROVED_WITHOUT_EXECUTION = 'approved_without_execution';
    public const STATUS_AUTO_APPROVED = 'auto_approved';
    public const STATUS_REJECTED = 'rejected';
    public const STATUS_EXECUTING = 'executing';
    public const STATUS_EXECUTED_PENDING_VERIFICATION = 'executed_pending_verification';
    public const STATUS_COMPENSATING = 'compensating';
    public const STATUS_MEASURING = 'measuring';
    public const STATUS_COMPLETED = 'completed';
    public const STATUS_FAILED = 'failed';
    public const STATUS_ROLLED_BACK = 'rolled_back';
    public const STATUS_ROLLBACK_INCOMPLETE = 'rollback_incomplete';
    public const STATUS_BLOCKED = 'blocked';
    public const STATUS_HALTED = 'halted';
    public const BATCH_STATUS_PENDING = 'pending';
    public const BATCH_STATUS_APPROVED = 'approved';
    public const BATCH_STATUS_APPROVED_WITHOUT_EXECUTION = 'approved_without_execution';
    public const BATCH_STATUS_AUTO_APPROVED = 'auto_approved';
    public const BATCH_STATUS_REJECTED = 'rejected';
    public const BATCH_STATUS_EXECUTING = 'executing';
    public const BATCH_STATUS_EXECUTED_PENDING_VERIFICATION = 'executed_pending_verification';
    public const BATCH_STATUS_COMPENSATING = 'compensating';
    public const BATCH_STATUS_MEASURING = 'measuring';
    public const BATCH_STATUS_COMPLETED = 'completed';
    public const BATCH_STATUS_FAILED = 'failed';
    public const BATCH_STATUS_ROLLED_BACK = 'rolled_back';
    public const BATCH_STATUS_ROLLBACK_INCOMPLETE = 'rollback_incomplete';
    public const BATCH_STATUS_BLOCKED = 'blocked';
    public const BATCH_STATUS_HALTED = 'halted';
    public const RESTORATION_SUMMARY_ALL_RECEIPTS_COMPENSATED_LATE = 'all_receipts_compensated_late';
    public const POLICY_DECISION_ALLOW = 'allow';
    public const POLICY_DECISION_REQUIRE_APPROVAL = 'require_approval';
    public const POLICY_DECISION_BLOCK = 'block';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_PENDING,
            self::STATUS_APPROVED,
            self::STATUS_APPROVED_WITHOUT_EXECUTION,
            self::STATUS_AUTO_APPROVED,
            self::STATUS_REJECTED,
            self::STATUS_EXECUTING,
            self::STATUS_EXECUTED_PENDING_VERIFICATION,
            self::STATUS_COMPENSATING,
            self::STATUS_MEASURING,
            self::STATUS_COMPLETED,
            self::STATUS_FAILED,
            self::STATUS_ROLLED_BACK,
            self::STATUS_ROLLBACK_INCOMPLETE,
            self::STATUS_BLOCKED,
            self::STATUS_HALTED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBatchStatusAllowableValues()
    {
        return [
            self::BATCH_STATUS_PENDING,
            self::BATCH_STATUS_APPROVED,
            self::BATCH_STATUS_APPROVED_WITHOUT_EXECUTION,
            self::BATCH_STATUS_AUTO_APPROVED,
            self::BATCH_STATUS_REJECTED,
            self::BATCH_STATUS_EXECUTING,
            self::BATCH_STATUS_EXECUTED_PENDING_VERIFICATION,
            self::BATCH_STATUS_COMPENSATING,
            self::BATCH_STATUS_MEASURING,
            self::BATCH_STATUS_COMPLETED,
            self::BATCH_STATUS_FAILED,
            self::BATCH_STATUS_ROLLED_BACK,
            self::BATCH_STATUS_ROLLBACK_INCOMPLETE,
            self::BATCH_STATUS_BLOCKED,
            self::BATCH_STATUS_HALTED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRestorationSummaryAllowableValues()
    {
        return [
            self::RESTORATION_SUMMARY_ALL_RECEIPTS_COMPENSATED_LATE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPolicyDecisionAllowableValues()
    {
        return [
            self::POLICY_DECISION_ALLOW,
            self::POLICY_DECISION_REQUIRE_APPROVAL,
            self::POLICY_DECISION_BLOCK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('workspace_id', $data ?? [], null);
        $this->setIfExists('platform_ad_account_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('batch_status', $data ?? [], null);
        $this->setIfExists('restoration_summary', $data ?? [], null);
        $this->setIfExists('policy_decision', $data ?? [], null);
        $this->setIfExists('policy_reasons', $data ?? [], null);
        $this->setIfExists('rationale', $data ?? [], null);
        $this->setIfExists('idempotency_key', $data ?? [], null);
        $this->setIfExists('actions', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['workspace_id'] === null) {
            $invalidProperties[] = "'workspace_id' can't be null";
        }
        if ($this->container['platform_ad_account_id'] === null) {
            $invalidProperties[] = "'platform_ad_account_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['batch_status'] === null) {
            $invalidProperties[] = "'batch_status' can't be null";
        }
        $allowedValues = $this->getBatchStatusAllowableValues();
        if (!is_null($this->container['batch_status']) && !in_array($this->container['batch_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'batch_status', must be one of '%s'",
                $this->container['batch_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['restoration_summary'] === null && !$this->isNullableSetToNull('restoration_summary')) {
            $invalidProperties[] = "'restoration_summary' is required";
        }
        $allowedValues = $this->getRestorationSummaryAllowableValues();
        if (!is_null($this->container['restoration_summary']) && !in_array($this->container['restoration_summary'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'restoration_summary', must be one of '%s'",
                $this->container['restoration_summary'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['policy_decision'] === null && !$this->isNullableSetToNull('policy_decision')) {
            $invalidProperties[] = "'policy_decision' is required";
        }
        $allowedValues = $this->getPolicyDecisionAllowableValues();
        if (!is_null($this->container['policy_decision']) && !in_array($this->container['policy_decision'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'policy_decision', must be one of '%s'",
                $this->container['policy_decision'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['policy_reasons'] === null) {
            $invalidProperties[] = "'policy_reasons' can't be null";
        }
        if ($this->container['rationale'] === null) {
            $invalidProperties[] = "'rationale' can't be null";
        }
        if ($this->container['idempotency_key'] === null) {
            $invalidProperties[] = "'idempotency_key' can't be null";
        }
        if ($this->container['actions'] === null) {
            $invalidProperties[] = "'actions' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets workspace_id
     *
     * @return int
     */
    public function getWorkspaceId()
    {
        return $this->container['workspace_id'];
    }

    /**
     * Sets workspace_id
     *
     * @param int $workspace_id workspace_id
     *
     * @return self
     */
    public function setWorkspaceId($workspace_id)
    {
        if (is_null($workspace_id)) {
            throw new \InvalidArgumentException('non-nullable workspace_id cannot be null');
        }
        $this->container['workspace_id'] = $workspace_id;

        return $this;
    }

    /**
     * Gets platform_ad_account_id
     *
     * @return int
     */
    public function getPlatformAdAccountId()
    {
        return $this->container['platform_ad_account_id'];
    }

    /**
     * Sets platform_ad_account_id
     *
     * @param int $platform_ad_account_id platform_ad_account_id
     *
     * @return self
     */
    public function setPlatformAdAccountId($platform_ad_account_id)
    {
        if (is_null($platform_ad_account_id)) {
            throw new \InvalidArgumentException('non-nullable platform_ad_account_id cannot be null');
        }
        $this->container['platform_ad_account_id'] = $platform_ad_account_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets batch_status
     *
     * @return string
     */
    public function getBatchStatus()
    {
        return $this->container['batch_status'];
    }

    /**
     * Sets batch_status
     *
     * @param string $batch_status batch_status
     *
     * @return self
     */
    public function setBatchStatus($batch_status)
    {
        if (is_null($batch_status)) {
            throw new \InvalidArgumentException('non-nullable batch_status cannot be null');
        }
        $allowedValues = $this->getBatchStatusAllowableValues();
        if (!in_array($batch_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'batch_status', must be one of '%s'",
                    $batch_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['batch_status'] = $batch_status;

        return $this;
    }

    /**
     * Gets restoration_summary
     *
     * @return string|null
     */
    public function getRestorationSummary()
    {
        return $this->container['restoration_summary'];
    }

    /**
     * Sets restoration_summary
     *
     * @param string|null $restoration_summary restoration_summary
     *
     * @return self
     */
    public function setRestorationSummary($restoration_summary)
    {
        if (is_null($restoration_summary)) {
            array_push($this->openAPINullablesSetToNull, 'restoration_summary');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('restoration_summary', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getRestorationSummaryAllowableValues();
        if (!is_null($restoration_summary) && !in_array($restoration_summary, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'restoration_summary', must be one of '%s'",
                    $restoration_summary,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['restoration_summary'] = $restoration_summary;

        return $this;
    }

    /**
     * Gets policy_decision
     *
     * @return string|null
     */
    public function getPolicyDecision()
    {
        return $this->container['policy_decision'];
    }

    /**
     * Sets policy_decision
     *
     * @param string|null $policy_decision policy_decision
     *
     * @return self
     */
    public function setPolicyDecision($policy_decision)
    {
        if (is_null($policy_decision)) {
            array_push($this->openAPINullablesSetToNull, 'policy_decision');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('policy_decision', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getPolicyDecisionAllowableValues();
        if (!is_null($policy_decision) && !in_array($policy_decision, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'policy_decision', must be one of '%s'",
                    $policy_decision,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['policy_decision'] = $policy_decision;

        return $this;
    }

    /**
     * Gets policy_reasons
     *
     * @return string[]
     */
    public function getPolicyReasons()
    {
        return $this->container['policy_reasons'];
    }

    /**
     * Sets policy_reasons
     *
     * @param string[] $policy_reasons policy_reasons
     *
     * @return self
     */
    public function setPolicyReasons($policy_reasons)
    {
        if (is_null($policy_reasons)) {
            throw new \InvalidArgumentException('non-nullable policy_reasons cannot be null');
        }
        $this->container['policy_reasons'] = $policy_reasons;

        return $this;
    }

    /**
     * Gets rationale
     *
     * @return string
     */
    public function getRationale()
    {
        return $this->container['rationale'];
    }

    /**
     * Sets rationale
     *
     * @param string $rationale rationale
     *
     * @return self
     */
    public function setRationale($rationale)
    {
        if (is_null($rationale)) {
            throw new \InvalidArgumentException('non-nullable rationale cannot be null');
        }
        $this->container['rationale'] = $rationale;

        return $this;
    }

    /**
     * Gets idempotency_key
     *
     * @return string
     */
    public function getIdempotencyKey()
    {
        return $this->container['idempotency_key'];
    }

    /**
     * Sets idempotency_key
     *
     * @param string $idempotency_key idempotency_key
     *
     * @return self
     */
    public function setIdempotencyKey($idempotency_key)
    {
        if (is_null($idempotency_key)) {
            throw new \InvalidArgumentException('non-nullable idempotency_key cannot be null');
        }
        $this->container['idempotency_key'] = $idempotency_key;

        return $this;
    }

    /**
     * Gets actions
     *
     * @return \Plainrouter\OpenAPI\Model\ActionReadItem[]
     */
    public function getActions()
    {
        return $this->container['actions'];
    }

    /**
     * Sets actions
     *
     * @param \Plainrouter\OpenAPI\Model\ActionReadItem[] $actions actions
     *
     * @return self
     */
    public function setActions($actions)
    {
        if (is_null($actions)) {
            throw new \InvalidArgumentException('non-nullable actions cannot be null');
        }
        $this->container['actions'] = $actions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


