<?php
/**
 * ActionDryRunReadDryRunActionsInnerAnyOf
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;

use \ArrayAccess;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * ActionDryRunReadDryRunActionsInnerAnyOf Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ActionDryRunReadDryRunActionsInnerAnyOf implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ActionDryRunRead_dry_run_actions_inner_anyOf';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'type' => 'string',
        'target_entity' => '\Plainrouter\OpenAPI\Model\ActionDryRunReadDryRunActionsInnerAnyOfTargetEntity',
        'status' => 'string',
        'policy_decision' => 'string',
        'policy_reasons' => 'string[]',
        'approval_required' => 'bool',
        'would_auto_execute' => 'bool',
        'diff' => '\Plainrouter\OpenAPI\Model\ActionDryRunReadDryRunActionsInnerAnyOfDiff'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'type' => null,
        'target_entity' => null,
        'status' => null,
        'policy_decision' => null,
        'policy_reasons' => null,
        'approval_required' => null,
        'would_auto_execute' => null,
        'diff' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'type' => false,
        'target_entity' => false,
        'status' => false,
        'policy_decision' => false,
        'policy_reasons' => false,
        'approval_required' => false,
        'would_auto_execute' => false,
        'diff' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'type' => 'type',
        'target_entity' => 'target_entity',
        'status' => 'status',
        'policy_decision' => 'policy_decision',
        'policy_reasons' => 'policy_reasons',
        'approval_required' => 'approval_required',
        'would_auto_execute' => 'would_auto_execute',
        'diff' => 'diff'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'type' => 'setType',
        'target_entity' => 'setTargetEntity',
        'status' => 'setStatus',
        'policy_decision' => 'setPolicyDecision',
        'policy_reasons' => 'setPolicyReasons',
        'approval_required' => 'setApprovalRequired',
        'would_auto_execute' => 'setWouldAutoExecute',
        'diff' => 'setDiff'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'type' => 'getType',
        'target_entity' => 'getTargetEntity',
        'status' => 'getStatus',
        'policy_decision' => 'getPolicyDecision',
        'policy_reasons' => 'getPolicyReasons',
        'approval_required' => 'getApprovalRequired',
        'would_auto_execute' => 'getWouldAutoExecute',
        'diff' => 'getDiff'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_INCREASE_BUDGET = 'increase_budget';
    public const TYPE_DECREASE_BUDGET = 'decrease_budget';
    public const TYPE_PAUSE = 'pause';
    public const TYPE_RESUME = 'resume';
    public const TYPE_REPLACE_CREATIVE = 'replace_creative';
    public const TYPE_SHIFT_SPEND = 'shift_spend';
    public const TYPE_ROLLBACK = 'rollback';
    public const TYPE_CREATE_CAMPAIGN = 'create_campaign';
    public const TYPE_CREATE_AD_SET = 'create_ad_set';
    public const TYPE_CREATE_AD = 'create_ad';
    public const TYPE_UPLOAD_ASSET = 'upload_asset';
    public const TYPE_ADJUST_BUDGET = 'adjust_budget';
    public const TYPE_SET_STATUS = 'set_status';
    public const TYPE_DUPLICATE_AD_WITH_CREATIVE = 'duplicate_ad_with_creative';
    public const TYPE_DUPLICATE_ADSET = 'duplicate_adset';
    public const TYPE_DUPLICATE_AD_WITH_CREATIVE_V2 = 'duplicate_ad_with_creative_v2';
    public const STATUS_EVALUATED = 'evaluated';
    public const POLICY_DECISION_ALLOW = 'allow';
    public const POLICY_DECISION_REQUIRE_APPROVAL = 'require_approval';
    public const POLICY_DECISION_BLOCK = 'block';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_INCREASE_BUDGET,
            self::TYPE_DECREASE_BUDGET,
            self::TYPE_PAUSE,
            self::TYPE_RESUME,
            self::TYPE_REPLACE_CREATIVE,
            self::TYPE_SHIFT_SPEND,
            self::TYPE_ROLLBACK,
            self::TYPE_CREATE_CAMPAIGN,
            self::TYPE_CREATE_AD_SET,
            self::TYPE_CREATE_AD,
            self::TYPE_UPLOAD_ASSET,
            self::TYPE_ADJUST_BUDGET,
            self::TYPE_SET_STATUS,
            self::TYPE_DUPLICATE_AD_WITH_CREATIVE,
            self::TYPE_DUPLICATE_ADSET,
            self::TYPE_DUPLICATE_AD_WITH_CREATIVE_V2,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_EVALUATED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPolicyDecisionAllowableValues()
    {
        return [
            self::POLICY_DECISION_ALLOW,
            self::POLICY_DECISION_REQUIRE_APPROVAL,
            self::POLICY_DECISION_BLOCK,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('target_entity', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('policy_decision', $data ?? [], null);
        $this->setIfExists('policy_reasons', $data ?? [], null);
        $this->setIfExists('approval_required', $data ?? [], null);
        $this->setIfExists('would_auto_execute', $data ?? [], null);
        $this->setIfExists('diff', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['target_entity'] === null) {
            $invalidProperties[] = "'target_entity' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['policy_decision'] === null) {
            $invalidProperties[] = "'policy_decision' can't be null";
        }
        $allowedValues = $this->getPolicyDecisionAllowableValues();
        if (!is_null($this->container['policy_decision']) && !in_array($this->container['policy_decision'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'policy_decision', must be one of '%s'",
                $this->container['policy_decision'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['policy_reasons'] === null) {
            $invalidProperties[] = "'policy_reasons' can't be null";
        }
        if ($this->container['approval_required'] === null) {
            $invalidProperties[] = "'approval_required' can't be null";
        }
        if ($this->container['would_auto_execute'] === null) {
            $invalidProperties[] = "'would_auto_execute' can't be null";
        }
        if ($this->container['diff'] === null) {
            $invalidProperties[] = "'diff' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets target_entity
     *
     * @return \Plainrouter\OpenAPI\Model\ActionDryRunReadDryRunActionsInnerAnyOfTargetEntity
     */
    public function getTargetEntity()
    {
        return $this->container['target_entity'];
    }

    /**
     * Sets target_entity
     *
     * @param \Plainrouter\OpenAPI\Model\ActionDryRunReadDryRunActionsInnerAnyOfTargetEntity $target_entity target_entity
     *
     * @return self
     */
    public function setTargetEntity($target_entity)
    {
        if (is_null($target_entity)) {
            throw new \InvalidArgumentException('non-nullable target_entity cannot be null');
        }
        $this->container['target_entity'] = $target_entity;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets policy_decision
     *
     * @return string
     */
    public function getPolicyDecision()
    {
        return $this->container['policy_decision'];
    }

    /**
     * Sets policy_decision
     *
     * @param string $policy_decision policy_decision
     *
     * @return self
     */
    public function setPolicyDecision($policy_decision)
    {
        if (is_null($policy_decision)) {
            throw new \InvalidArgumentException('non-nullable policy_decision cannot be null');
        }
        $allowedValues = $this->getPolicyDecisionAllowableValues();
        if (!in_array($policy_decision, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'policy_decision', must be one of '%s'",
                    $policy_decision,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['policy_decision'] = $policy_decision;

        return $this;
    }

    /**
     * Gets policy_reasons
     *
     * @return string[]
     */
    public function getPolicyReasons()
    {
        return $this->container['policy_reasons'];
    }

    /**
     * Sets policy_reasons
     *
     * @param string[] $policy_reasons policy_reasons
     *
     * @return self
     */
    public function setPolicyReasons($policy_reasons)
    {
        if (is_null($policy_reasons)) {
            throw new \InvalidArgumentException('non-nullable policy_reasons cannot be null');
        }
        $this->container['policy_reasons'] = $policy_reasons;

        return $this;
    }

    /**
     * Gets approval_required
     *
     * @return bool
     */
    public function getApprovalRequired()
    {
        return $this->container['approval_required'];
    }

    /**
     * Sets approval_required
     *
     * @param bool $approval_required approval_required
     *
     * @return self
     */
    public function setApprovalRequired($approval_required)
    {
        if (is_null($approval_required)) {
            throw new \InvalidArgumentException('non-nullable approval_required cannot be null');
        }
        $this->container['approval_required'] = $approval_required;

        return $this;
    }

    /**
     * Gets would_auto_execute
     *
     * @return bool
     */
    public function getWouldAutoExecute()
    {
        return $this->container['would_auto_execute'];
    }

    /**
     * Sets would_auto_execute
     *
     * @param bool $would_auto_execute would_auto_execute
     *
     * @return self
     */
    public function setWouldAutoExecute($would_auto_execute)
    {
        if (is_null($would_auto_execute)) {
            throw new \InvalidArgumentException('non-nullable would_auto_execute cannot be null');
        }
        $this->container['would_auto_execute'] = $would_auto_execute;

        return $this;
    }

    /**
     * Gets diff
     *
     * @return \Plainrouter\OpenAPI\Model\ActionDryRunReadDryRunActionsInnerAnyOfDiff
     */
    public function getDiff()
    {
        return $this->container['diff'];
    }

    /**
     * Sets diff
     *
     * @param \Plainrouter\OpenAPI\Model\ActionDryRunReadDryRunActionsInnerAnyOfDiff $diff diff
     *
     * @return self
     */
    public function setDiff($diff)
    {
        if (is_null($diff)) {
            throw new \InvalidArgumentException('non-nullable diff cannot be null');
        }
        $this->container['diff'] = $diff;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


