<?php
/**
 * AdTestVerdictMemberRead
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;

use \ArrayAccess;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * AdTestVerdictMemberRead Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdTestVerdictMemberRead implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AdTestVerdictMemberRead';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ad_id' => 'string',
        'state' => 'string',
        'rank' => 'int',
        'spend' => 'string',
        'impressions' => 'int',
        'counted_arrivals' => 'int',
        'recorded_conversions' => 'int',
        'admitted_conversions' => 'int',
        'spend_per_recorded_conversion' => 'string',
        'covered_days' => '\DateTime[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ad_id' => null,
        'state' => null,
        'rank' => null,
        'spend' => null,
        'impressions' => null,
        'counted_arrivals' => null,
        'recorded_conversions' => null,
        'admitted_conversions' => null,
        'spend_per_recorded_conversion' => null,
        'covered_days' => 'date'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ad_id' => false,
        'state' => false,
        'rank' => true,
        'spend' => true,
        'impressions' => true,
        'counted_arrivals' => true,
        'recorded_conversions' => true,
        'admitted_conversions' => true,
        'spend_per_recorded_conversion' => true,
        'covered_days' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ad_id' => 'ad_id',
        'state' => 'state',
        'rank' => 'rank',
        'spend' => 'spend',
        'impressions' => 'impressions',
        'counted_arrivals' => 'counted_arrivals',
        'recorded_conversions' => 'recorded_conversions',
        'admitted_conversions' => 'admitted_conversions',
        'spend_per_recorded_conversion' => 'spend_per_recorded_conversion',
        'covered_days' => 'covered_days'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ad_id' => 'setAdId',
        'state' => 'setState',
        'rank' => 'setRank',
        'spend' => 'setSpend',
        'impressions' => 'setImpressions',
        'counted_arrivals' => 'setCountedArrivals',
        'recorded_conversions' => 'setRecordedConversions',
        'admitted_conversions' => 'setAdmittedConversions',
        'spend_per_recorded_conversion' => 'setSpendPerRecordedConversion',
        'covered_days' => 'setCoveredDays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ad_id' => 'getAdId',
        'state' => 'getState',
        'rank' => 'getRank',
        'spend' => 'getSpend',
        'impressions' => 'getImpressions',
        'counted_arrivals' => 'getCountedArrivals',
        'recorded_conversions' => 'getRecordedConversions',
        'admitted_conversions' => 'getAdmittedConversions',
        'spend_per_recorded_conversion' => 'getSpendPerRecordedConversion',
        'covered_days' => 'getCoveredDays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const STATE_NOT_DELIVERED = 'not_delivered';
    public const STATE_INSUFFICIENT = 'insufficient';
    public const STATE_RANKED = 'ranked';
    public const STATE_FACTS_UNAVAILABLE = 'facts_unavailable';
    public const STATE_HALTED = 'halted';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_NOT_DELIVERED,
            self::STATE_INSUFFICIENT,
            self::STATE_RANKED,
            self::STATE_FACTS_UNAVAILABLE,
            self::STATE_HALTED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ad_id', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('rank', $data ?? [], null);
        $this->setIfExists('spend', $data ?? [], null);
        $this->setIfExists('impressions', $data ?? [], null);
        $this->setIfExists('counted_arrivals', $data ?? [], null);
        $this->setIfExists('recorded_conversions', $data ?? [], null);
        $this->setIfExists('admitted_conversions', $data ?? [], null);
        $this->setIfExists('spend_per_recorded_conversion', $data ?? [], null);
        $this->setIfExists('covered_days', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['ad_id'] === null) {
            $invalidProperties[] = "'ad_id' can't be null";
        }
        if ((mb_strlen($this->container['ad_id']) > 128)) {
            $invalidProperties[] = "invalid value for 'ad_id', the character length must be smaller than or equal to 128.";
        }

        if (!preg_match("/^[0-9]+$/", $this->container['ad_id'])) {
            $invalidProperties[] = "invalid value for 'ad_id', must be conform to the pattern /^[0-9]+$/.";
        }

        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($this->container['state']) && !in_array($this->container['state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'state', must be one of '%s'",
                $this->container['state'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['rank'] === null && !$this->isNullableSetToNull('rank')) {
            $invalidProperties[] = "'rank' is required";
        }
        if ($this->container['spend'] === null && !$this->isNullableSetToNull('spend')) {
            $invalidProperties[] = "'spend' is required";
        }
        if ($this->container['impressions'] === null && !$this->isNullableSetToNull('impressions')) {
            $invalidProperties[] = "'impressions' is required";
        }
        if ($this->container['counted_arrivals'] === null && !$this->isNullableSetToNull('counted_arrivals')) {
            $invalidProperties[] = "'counted_arrivals' is required";
        }
        if ($this->container['recorded_conversions'] === null && !$this->isNullableSetToNull('recorded_conversions')) {
            $invalidProperties[] = "'recorded_conversions' is required";
        }
        if ($this->container['admitted_conversions'] === null && !$this->isNullableSetToNull('admitted_conversions')) {
            $invalidProperties[] = "'admitted_conversions' is required";
        }
        if ($this->container['spend_per_recorded_conversion'] === null && !$this->isNullableSetToNull('spend_per_recorded_conversion')) {
            $invalidProperties[] = "'spend_per_recorded_conversion' is required";
        }
        if ($this->container['covered_days'] === null) {
            $invalidProperties[] = "'covered_days' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ad_id
     *
     * @return string
     */
    public function getAdId()
    {
        return $this->container['ad_id'];
    }

    /**
     * Sets ad_id
     *
     * @param string $ad_id ad_id
     *
     * @return self
     */
    public function setAdId($ad_id)
    {
        if (is_null($ad_id)) {
            throw new \InvalidArgumentException('non-nullable ad_id cannot be null');
        }
        if ((mb_strlen($ad_id) > 128)) {
            throw new \InvalidArgumentException('invalid length for $ad_id when calling AdTestVerdictMemberRead., must be smaller than or equal to 128.');
        }
        if ((!preg_match("/^[0-9]+$/", ObjectSerializer::toString($ad_id)))) {
            throw new \InvalidArgumentException("invalid value for \$ad_id when calling AdTestVerdictMemberRead., must conform to the pattern /^[0-9]+$/.");
        }

        $this->container['ad_id'] = $ad_id;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!in_array($state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'state', must be one of '%s'",
                    $state,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets rank
     *
     * @return int|null
     */
    public function getRank()
    {
        return $this->container['rank'];
    }

    /**
     * Sets rank
     *
     * @param int|null $rank rank
     *
     * @return self
     */
    public function setRank($rank)
    {
        if (is_null($rank)) {
            array_push($this->openAPINullablesSetToNull, 'rank');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('rank', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['rank'] = $rank;

        return $this;
    }

    /**
     * Gets spend
     *
     * @return string|null
     */
    public function getSpend()
    {
        return $this->container['spend'];
    }

    /**
     * Sets spend
     *
     * @param string|null $spend spend
     *
     * @return self
     */
    public function setSpend($spend)
    {
        if (is_null($spend)) {
            array_push($this->openAPINullablesSetToNull, 'spend');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spend', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spend'] = $spend;

        return $this;
    }

    /**
     * Gets impressions
     *
     * @return int|null
     */
    public function getImpressions()
    {
        return $this->container['impressions'];
    }

    /**
     * Sets impressions
     *
     * @param int|null $impressions impressions
     *
     * @return self
     */
    public function setImpressions($impressions)
    {
        if (is_null($impressions)) {
            array_push($this->openAPINullablesSetToNull, 'impressions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('impressions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['impressions'] = $impressions;

        return $this;
    }

    /**
     * Gets counted_arrivals
     *
     * @return int|null
     */
    public function getCountedArrivals()
    {
        return $this->container['counted_arrivals'];
    }

    /**
     * Sets counted_arrivals
     *
     * @param int|null $counted_arrivals counted_arrivals
     *
     * @return self
     */
    public function setCountedArrivals($counted_arrivals)
    {
        if (is_null($counted_arrivals)) {
            array_push($this->openAPINullablesSetToNull, 'counted_arrivals');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('counted_arrivals', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['counted_arrivals'] = $counted_arrivals;

        return $this;
    }

    /**
     * Gets recorded_conversions
     *
     * @return int|null
     */
    public function getRecordedConversions()
    {
        return $this->container['recorded_conversions'];
    }

    /**
     * Sets recorded_conversions
     *
     * @param int|null $recorded_conversions PlainRouter recorded consented conversions of this Test event.
     *
     * @return self
     */
    public function setRecordedConversions($recorded_conversions)
    {
        if (is_null($recorded_conversions)) {
            array_push($this->openAPINullablesSetToNull, 'recorded_conversions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('recorded_conversions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['recorded_conversions'] = $recorded_conversions;

        return $this;
    }

    /**
     * Gets admitted_conversions
     *
     * @return int|null
     */
    public function getAdmittedConversions()
    {
        return $this->container['admitted_conversions'];
    }

    /**
     * Sets admitted_conversions
     *
     * @param int|null $admitted_conversions Admitted conversions are shown beside recorded conversions and are never substituted for them.
     *
     * @return self
     */
    public function setAdmittedConversions($admitted_conversions)
    {
        if (is_null($admitted_conversions)) {
            array_push($this->openAPINullablesSetToNull, 'admitted_conversions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('admitted_conversions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['admitted_conversions'] = $admitted_conversions;

        return $this;
    }

    /**
     * Gets spend_per_recorded_conversion
     *
     * @return string|null
     */
    public function getSpendPerRecordedConversion()
    {
        return $this->container['spend_per_recorded_conversion'];
    }

    /**
     * Sets spend_per_recorded_conversion
     *
     * @param string|null $spend_per_recorded_conversion Major-unit spend divided by PlainRouter recorded conversions; used only to compare members within this Test.
     *
     * @return self
     */
    public function setSpendPerRecordedConversion($spend_per_recorded_conversion)
    {
        if (is_null($spend_per_recorded_conversion)) {
            array_push($this->openAPINullablesSetToNull, 'spend_per_recorded_conversion');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spend_per_recorded_conversion', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spend_per_recorded_conversion'] = $spend_per_recorded_conversion;

        return $this;
    }

    /**
     * Gets covered_days
     *
     * @return \DateTime[]
     */
    public function getCoveredDays()
    {
        return $this->container['covered_days'];
    }

    /**
     * Sets covered_days
     *
     * @param \DateTime[] $covered_days covered_days
     *
     * @return self
     */
    public function setCoveredDays($covered_days)
    {
        if (is_null($covered_days)) {
            throw new \InvalidArgumentException('non-nullable covered_days cannot be null');
        }
        $this->container['covered_days'] = $covered_days;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


