<?php
/**
 * AdTestCreateReadTestVerdictHaltDetails
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;

use \ArrayAccess;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * AdTestCreateReadTestVerdictHaltDetails Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AdTestCreateReadTestVerdictHaltDetails implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'AdTestCreateRead_test_verdict_halt_details';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'ad_id' => 'string',
        'effective_status' => 'string',
        'date' => '\DateTime',
        'link_clicks' => 'int',
        'counted_arrivals' => 'int',
        'ad_test_member_id' => 'string',
        'baseline' => '\Plainrouter\OpenAPI\Model\AdTestCreateReadTestVerdictHaltDetailsBaseline',
        'observed_destinations' => '\Plainrouter\OpenAPI\Model\AdTestCreateReadTestVerdictHaltDetailsObservedDestinationsInner[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'ad_id' => null,
        'effective_status' => null,
        'date' => 'date',
        'link_clicks' => null,
        'counted_arrivals' => null,
        'ad_test_member_id' => null,
        'baseline' => null,
        'observed_destinations' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'ad_id' => false,
        'effective_status' => false,
        'date' => false,
        'link_clicks' => false,
        'counted_arrivals' => false,
        'ad_test_member_id' => false,
        'baseline' => false,
        'observed_destinations' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'ad_id' => 'ad_id',
        'effective_status' => 'effective_status',
        'date' => 'date',
        'link_clicks' => 'link_clicks',
        'counted_arrivals' => 'counted_arrivals',
        'ad_test_member_id' => 'ad_test_member_id',
        'baseline' => 'baseline',
        'observed_destinations' => 'observed_destinations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'ad_id' => 'setAdId',
        'effective_status' => 'setEffectiveStatus',
        'date' => 'setDate',
        'link_clicks' => 'setLinkClicks',
        'counted_arrivals' => 'setCountedArrivals',
        'ad_test_member_id' => 'setAdTestMemberId',
        'baseline' => 'setBaseline',
        'observed_destinations' => 'setObservedDestinations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'ad_id' => 'getAdId',
        'effective_status' => 'getEffectiveStatus',
        'date' => 'getDate',
        'link_clicks' => 'getLinkClicks',
        'counted_arrivals' => 'getCountedArrivals',
        'ad_test_member_id' => 'getAdTestMemberId',
        'baseline' => 'getBaseline',
        'observed_destinations' => 'getObservedDestinations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const EFFECTIVE_STATUS_DISAPPROVED = 'DISAPPROVED';
    public const EFFECTIVE_STATUS_WITH_ISSUES = 'WITH_ISSUES';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEffectiveStatusAllowableValues()
    {
        return [
            self::EFFECTIVE_STATUS_DISAPPROVED,
            self::EFFECTIVE_STATUS_WITH_ISSUES,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('ad_id', $data ?? [], null);
        $this->setIfExists('effective_status', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('link_clicks', $data ?? [], null);
        $this->setIfExists('counted_arrivals', $data ?? [], null);
        $this->setIfExists('ad_test_member_id', $data ?? [], null);
        $this->setIfExists('baseline', $data ?? [], null);
        $this->setIfExists('observed_destinations', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getEffectiveStatusAllowableValues();
        if (!is_null($this->container['effective_status']) && !in_array($this->container['effective_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'effective_status', must be one of '%s'",
                $this->container['effective_status'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['ad_test_member_id']) && (mb_strlen($this->container['ad_test_member_id']) > 26)) {
            $invalidProperties[] = "invalid value for 'ad_test_member_id', the character length must be smaller than or equal to 26.";
        }

        if (!is_null($this->container['ad_test_member_id']) && (mb_strlen($this->container['ad_test_member_id']) < 26)) {
            $invalidProperties[] = "invalid value for 'ad_test_member_id', the character length must be bigger than or equal to 26.";
        }

        if (!is_null($this->container['ad_test_member_id']) && !preg_match("/^[0-7][0-9a-hjkmnp-tv-z]{25}$/", $this->container['ad_test_member_id'])) {
            $invalidProperties[] = "invalid value for 'ad_test_member_id', must be conform to the pattern /^[0-7][0-9a-hjkmnp-tv-z]{25}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets ad_id
     *
     * @return string|null
     */
    public function getAdId()
    {
        return $this->container['ad_id'];
    }

    /**
     * Sets ad_id
     *
     * @param string|null $ad_id ad_id
     *
     * @return self
     */
    public function setAdId($ad_id)
    {
        if (is_null($ad_id)) {
            throw new \InvalidArgumentException('non-nullable ad_id cannot be null');
        }
        $this->container['ad_id'] = $ad_id;

        return $this;
    }

    /**
     * Gets effective_status
     *
     * @return string|null
     */
    public function getEffectiveStatus()
    {
        return $this->container['effective_status'];
    }

    /**
     * Sets effective_status
     *
     * @param string|null $effective_status effective_status
     *
     * @return self
     */
    public function setEffectiveStatus($effective_status)
    {
        if (is_null($effective_status)) {
            throw new \InvalidArgumentException('non-nullable effective_status cannot be null');
        }
        $allowedValues = $this->getEffectiveStatusAllowableValues();
        if (!in_array($effective_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'effective_status', must be one of '%s'",
                    $effective_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['effective_status'] = $effective_status;

        return $this;
    }

    /**
     * Gets date
     *
     * @return \DateTime|null
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param \DateTime|null $date date
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets link_clicks
     *
     * @return int|null
     */
    public function getLinkClicks()
    {
        return $this->container['link_clicks'];
    }

    /**
     * Sets link_clicks
     *
     * @param int|null $link_clicks link_clicks
     *
     * @return self
     */
    public function setLinkClicks($link_clicks)
    {
        if (is_null($link_clicks)) {
            throw new \InvalidArgumentException('non-nullable link_clicks cannot be null');
        }
        $this->container['link_clicks'] = $link_clicks;

        return $this;
    }

    /**
     * Gets counted_arrivals
     *
     * @return int|null
     */
    public function getCountedArrivals()
    {
        return $this->container['counted_arrivals'];
    }

    /**
     * Sets counted_arrivals
     *
     * @param int|null $counted_arrivals counted_arrivals
     *
     * @return self
     */
    public function setCountedArrivals($counted_arrivals)
    {
        if (is_null($counted_arrivals)) {
            throw new \InvalidArgumentException('non-nullable counted_arrivals cannot be null');
        }
        $this->container['counted_arrivals'] = $counted_arrivals;

        return $this;
    }

    /**
     * Gets ad_test_member_id
     *
     * @return string|null
     */
    public function getAdTestMemberId()
    {
        return $this->container['ad_test_member_id'];
    }

    /**
     * Sets ad_test_member_id
     *
     * @param string|null $ad_test_member_id ad_test_member_id
     *
     * @return self
     */
    public function setAdTestMemberId($ad_test_member_id)
    {
        if (is_null($ad_test_member_id)) {
            throw new \InvalidArgumentException('non-nullable ad_test_member_id cannot be null');
        }
        if ((mb_strlen($ad_test_member_id) > 26)) {
            throw new \InvalidArgumentException('invalid length for $ad_test_member_id when calling AdTestCreateReadTestVerdictHaltDetails., must be smaller than or equal to 26.');
        }
        if ((mb_strlen($ad_test_member_id) < 26)) {
            throw new \InvalidArgumentException('invalid length for $ad_test_member_id when calling AdTestCreateReadTestVerdictHaltDetails., must be bigger than or equal to 26.');
        }
        if ((!preg_match("/^[0-7][0-9a-hjkmnp-tv-z]{25}$/", ObjectSerializer::toString($ad_test_member_id)))) {
            throw new \InvalidArgumentException("invalid value for \$ad_test_member_id when calling AdTestCreateReadTestVerdictHaltDetails., must conform to the pattern /^[0-7][0-9a-hjkmnp-tv-z]{25}$/.");
        }

        $this->container['ad_test_member_id'] = $ad_test_member_id;

        return $this;
    }

    /**
     * Gets baseline
     *
     * @return \Plainrouter\OpenAPI\Model\AdTestCreateReadTestVerdictHaltDetailsBaseline|null
     */
    public function getBaseline()
    {
        return $this->container['baseline'];
    }

    /**
     * Sets baseline
     *
     * @param \Plainrouter\OpenAPI\Model\AdTestCreateReadTestVerdictHaltDetailsBaseline|null $baseline baseline
     *
     * @return self
     */
    public function setBaseline($baseline)
    {
        if (is_null($baseline)) {
            throw new \InvalidArgumentException('non-nullable baseline cannot be null');
        }
        $this->container['baseline'] = $baseline;

        return $this;
    }

    /**
     * Gets observed_destinations
     *
     * @return \Plainrouter\OpenAPI\Model\AdTestCreateReadTestVerdictHaltDetailsObservedDestinationsInner[]|null
     */
    public function getObservedDestinations()
    {
        return $this->container['observed_destinations'];
    }

    /**
     * Sets observed_destinations
     *
     * @param \Plainrouter\OpenAPI\Model\AdTestCreateReadTestVerdictHaltDetailsObservedDestinationsInner[]|null $observed_destinations observed_destinations
     *
     * @return self
     */
    public function setObservedDestinations($observed_destinations)
    {
        if (is_null($observed_destinations)) {
            throw new \InvalidArgumentException('non-nullable observed_destinations cannot be null');
        }
        $this->container['observed_destinations'] = $observed_destinations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


