<?php
/**
 * DeploymentPlanReadCreativesInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;

use \ArrayAccess;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * DeploymentPlanReadCreativesInner Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DeploymentPlanReadCreativesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'DeploymentPlanRead_creatives_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'position' => 'int',
        'copy' => '\Plainrouter\OpenAPI\Model\DeploymentPlanReadCreativesInnerCopy',
        'landing_page' => 'string',
        'resolved_copy' => '\Plainrouter\OpenAPI\Model\DeploymentPlanReadCopy',
        'resolved_landing_page' => 'string',
        'copy_differs' => 'bool',
        'landing_page_differs' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'position' => null,
        'copy' => null,
        'landing_page' => null,
        'resolved_copy' => null,
        'resolved_landing_page' => null,
        'copy_differs' => null,
        'landing_page_differs' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'position' => false,
        'copy' => true,
        'landing_page' => true,
        'resolved_copy' => true,
        'resolved_landing_page' => false,
        'copy_differs' => false,
        'landing_page_differs' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'position' => 'position',
        'copy' => 'copy',
        'landing_page' => 'landing_page',
        'resolved_copy' => 'resolved_copy',
        'resolved_landing_page' => 'resolved_landing_page',
        'copy_differs' => 'copy_differs',
        'landing_page_differs' => 'landing_page_differs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'position' => 'setPosition',
        'copy' => 'setCopy',
        'landing_page' => 'setLandingPage',
        'resolved_copy' => 'setResolvedCopy',
        'resolved_landing_page' => 'setResolvedLandingPage',
        'copy_differs' => 'setCopyDiffers',
        'landing_page_differs' => 'setLandingPageDiffers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'position' => 'getPosition',
        'copy' => 'getCopy',
        'landing_page' => 'getLandingPage',
        'resolved_copy' => 'getResolvedCopy',
        'resolved_landing_page' => 'getResolvedLandingPage',
        'copy_differs' => 'getCopyDiffers',
        'landing_page_differs' => 'getLandingPageDiffers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('copy', $data ?? [], null);
        $this->setIfExists('landing_page', $data ?? [], null);
        $this->setIfExists('resolved_copy', $data ?? [], null);
        $this->setIfExists('resolved_landing_page', $data ?? [], null);
        $this->setIfExists('copy_differs', $data ?? [], null);
        $this->setIfExists('landing_page_differs', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['position'] === null) {
            $invalidProperties[] = "'position' can't be null";
        }
        if ($this->container['copy'] === null && !$this->isNullableSetToNull('copy')) {
            $invalidProperties[] = "'copy' is required";
        }
        if ($this->container['landing_page'] === null && !$this->isNullableSetToNull('landing_page')) {
            $invalidProperties[] = "'landing_page' is required";
        }
        if (!is_null($this->container['landing_page']) && (mb_strlen($this->container['landing_page']) > 2048)) {
            $invalidProperties[] = "invalid value for 'landing_page', the character length must be smaller than or equal to 2048.";
        }

        if ($this->container['resolved_copy'] === null && !$this->isNullableSetToNull('resolved_copy')) {
            $invalidProperties[] = "'resolved_copy' is required";
        }
        if ($this->container['resolved_landing_page'] === null) {
            $invalidProperties[] = "'resolved_landing_page' can't be null";
        }
        if ($this->container['copy_differs'] === null) {
            $invalidProperties[] = "'copy_differs' can't be null";
        }
        if ($this->container['landing_page_differs'] === null) {
            $invalidProperties[] = "'landing_page_differs' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets position
     *
     * @return int
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        if (is_null($position)) {
            throw new \InvalidArgumentException('non-nullable position cannot be null');
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets copy
     *
     * @return \Plainrouter\OpenAPI\Model\DeploymentPlanReadCreativesInnerCopy|null
     */
    public function getCopy()
    {
        return $this->container['copy'];
    }

    /**
     * Sets copy
     *
     * @param \Plainrouter\OpenAPI\Model\DeploymentPlanReadCreativesInnerCopy|null $copy copy
     *
     * @return self
     */
    public function setCopy($copy)
    {
        if (is_null($copy)) {
            array_push($this->openAPINullablesSetToNull, 'copy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('copy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['copy'] = $copy;

        return $this;
    }

    /**
     * Gets landing_page
     *
     * @return string|null
     */
    public function getLandingPage()
    {
        return $this->container['landing_page'];
    }

    /**
     * Sets landing_page
     *
     * @param string|null $landing_page Optional per-ad HTTPS landing URL override; null uses the plan landing URL.
     *
     * @return self
     */
    public function setLandingPage($landing_page)
    {
        if (is_null($landing_page)) {
            array_push($this->openAPINullablesSetToNull, 'landing_page');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('landing_page', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($landing_page) && (mb_strlen($landing_page) > 2048)) {
            throw new \InvalidArgumentException('invalid length for $landing_page when calling DeploymentPlanReadCreativesInner., must be smaller than or equal to 2048.');
        }

        $this->container['landing_page'] = $landing_page;

        return $this;
    }

    /**
     * Gets resolved_copy
     *
     * @return \Plainrouter\OpenAPI\Model\DeploymentPlanReadCopy|null
     */
    public function getResolvedCopy()
    {
        return $this->container['resolved_copy'];
    }

    /**
     * Sets resolved_copy
     *
     * @param \Plainrouter\OpenAPI\Model\DeploymentPlanReadCopy|null $resolved_copy resolved_copy
     *
     * @return self
     */
    public function setResolvedCopy($resolved_copy)
    {
        if (is_null($resolved_copy)) {
            array_push($this->openAPINullablesSetToNull, 'resolved_copy');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resolved_copy', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resolved_copy'] = $resolved_copy;

        return $this;
    }

    /**
     * Gets resolved_landing_page
     *
     * @return string
     */
    public function getResolvedLandingPage()
    {
        return $this->container['resolved_landing_page'];
    }

    /**
     * Sets resolved_landing_page
     *
     * @param string $resolved_landing_page resolved_landing_page
     *
     * @return self
     */
    public function setResolvedLandingPage($resolved_landing_page)
    {
        if (is_null($resolved_landing_page)) {
            throw new \InvalidArgumentException('non-nullable resolved_landing_page cannot be null');
        }
        $this->container['resolved_landing_page'] = $resolved_landing_page;

        return $this;
    }

    /**
     * Gets copy_differs
     *
     * @return bool
     */
    public function getCopyDiffers()
    {
        return $this->container['copy_differs'];
    }

    /**
     * Sets copy_differs
     *
     * @param bool $copy_differs copy_differs
     *
     * @return self
     */
    public function setCopyDiffers($copy_differs)
    {
        if (is_null($copy_differs)) {
            throw new \InvalidArgumentException('non-nullable copy_differs cannot be null');
        }
        $this->container['copy_differs'] = $copy_differs;

        return $this;
    }

    /**
     * Gets landing_page_differs
     *
     * @return bool
     */
    public function getLandingPageDiffers()
    {
        return $this->container['landing_page_differs'];
    }

    /**
     * Sets landing_page_differs
     *
     * @param bool $landing_page_differs landing_page_differs
     *
     * @return self
     */
    public function setLandingPageDiffers($landing_page_differs)
    {
        if (is_null($landing_page_differs)) {
            throw new \InvalidArgumentException('non-nullable landing_page_differs cannot be null');
        }
        $this->container['landing_page_differs'] = $landing_page_differs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


