<?php
/**
 * Event
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;

use \ArrayAccess;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * Event Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Event implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Event';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'string',
        'parent_event_id' => 'string',
        'event_name' => 'string',
        'event_time' => '\DateTime',
        'action_source' => 'string',
        'event_class' => 'string',
        'order_id' => 'string',
        'value_amount' => 'int',
        'value_currency' => 'string',
        'created_at' => '\DateTime',
        'consent_basis' => 'string',
        'measurement_class' => 'string',
        'attribution_join' => 'string',
        'enforcement_scope' => 'string',
        'consent_normalization_version' => 'string',
        'policy_class' => '\Plainrouter\OpenAPI\Model\JurisdictionPolicyClass',
        'traffic_class' => '\Plainrouter\OpenAPI\Model\TrafficClass',
        'workspace_id' => 'int',
        'consent' => 'string',
        'user_data_hashed' => '\Plainrouter\OpenAPI\Model\GetEvent200ResponseEventUserDataHashed',
        'click_ids' => 'string',
        'session' => 'string',
        'value_data' => 'string',
        'event_source' => 'string',
        'payload_expired' => 'bool',
        'consent_source' => 'string',
        'consent_ui_version' => 'int',
        'deliveries' => 'mixed[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'parent_event_id' => null,
        'event_name' => null,
        'event_time' => 'date-time',
        'action_source' => null,
        'event_class' => null,
        'order_id' => null,
        'value_amount' => null,
        'value_currency' => null,
        'created_at' => 'date-time',
        'consent_basis' => null,
        'measurement_class' => null,
        'attribution_join' => null,
        'enforcement_scope' => null,
        'consent_normalization_version' => null,
        'policy_class' => null,
        'traffic_class' => null,
        'workspace_id' => null,
        'consent' => null,
        'user_data_hashed' => null,
        'click_ids' => null,
        'session' => null,
        'value_data' => null,
        'event_source' => null,
        'payload_expired' => null,
        'consent_source' => null,
        'consent_ui_version' => null,
        'deliveries' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'parent_event_id' => true,
        'event_name' => false,
        'event_time' => false,
        'action_source' => false,
        'event_class' => false,
        'order_id' => true,
        'value_amount' => true,
        'value_currency' => true,
        'created_at' => false,
        'consent_basis' => false,
        'measurement_class' => false,
        'attribution_join' => false,
        'enforcement_scope' => false,
        'consent_normalization_version' => false,
        'policy_class' => false,
        'traffic_class' => false,
        'workspace_id' => false,
        'consent' => false,
        'user_data_hashed' => true,
        'click_ids' => false,
        'session' => false,
        'value_data' => false,
        'event_source' => false,
        'payload_expired' => false,
        'consent_source' => false,
        'consent_ui_version' => false,
        'deliveries' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'parent_event_id' => 'parent_event_id',
        'event_name' => 'event_name',
        'event_time' => 'event_time',
        'action_source' => 'action_source',
        'event_class' => 'event_class',
        'order_id' => 'order_id',
        'value_amount' => 'value_amount',
        'value_currency' => 'value_currency',
        'created_at' => 'created_at',
        'consent_basis' => 'consent_basis',
        'measurement_class' => 'measurement_class',
        'attribution_join' => 'attribution_join',
        'enforcement_scope' => 'enforcement_scope',
        'consent_normalization_version' => 'consent_normalization_version',
        'policy_class' => 'policy_class',
        'traffic_class' => 'traffic_class',
        'workspace_id' => 'workspace_id',
        'consent' => 'consent',
        'user_data_hashed' => 'user_data_hashed',
        'click_ids' => 'click_ids',
        'session' => 'session',
        'value_data' => 'value_data',
        'event_source' => 'event_source',
        'payload_expired' => 'payload_expired',
        'consent_source' => 'consent_source',
        'consent_ui_version' => 'consent_ui_version',
        'deliveries' => 'deliveries'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'parent_event_id' => 'setParentEventId',
        'event_name' => 'setEventName',
        'event_time' => 'setEventTime',
        'action_source' => 'setActionSource',
        'event_class' => 'setEventClass',
        'order_id' => 'setOrderId',
        'value_amount' => 'setValueAmount',
        'value_currency' => 'setValueCurrency',
        'created_at' => 'setCreatedAt',
        'consent_basis' => 'setConsentBasis',
        'measurement_class' => 'setMeasurementClass',
        'attribution_join' => 'setAttributionJoin',
        'enforcement_scope' => 'setEnforcementScope',
        'consent_normalization_version' => 'setConsentNormalizationVersion',
        'policy_class' => 'setPolicyClass',
        'traffic_class' => 'setTrafficClass',
        'workspace_id' => 'setWorkspaceId',
        'consent' => 'setConsent',
        'user_data_hashed' => 'setUserDataHashed',
        'click_ids' => 'setClickIds',
        'session' => 'setSession',
        'value_data' => 'setValueData',
        'event_source' => 'setEventSource',
        'payload_expired' => 'setPayloadExpired',
        'consent_source' => 'setConsentSource',
        'consent_ui_version' => 'setConsentUiVersion',
        'deliveries' => 'setDeliveries'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'parent_event_id' => 'getParentEventId',
        'event_name' => 'getEventName',
        'event_time' => 'getEventTime',
        'action_source' => 'getActionSource',
        'event_class' => 'getEventClass',
        'order_id' => 'getOrderId',
        'value_amount' => 'getValueAmount',
        'value_currency' => 'getValueCurrency',
        'created_at' => 'getCreatedAt',
        'consent_basis' => 'getConsentBasis',
        'measurement_class' => 'getMeasurementClass',
        'attribution_join' => 'getAttributionJoin',
        'enforcement_scope' => 'getEnforcementScope',
        'consent_normalization_version' => 'getConsentNormalizationVersion',
        'policy_class' => 'getPolicyClass',
        'traffic_class' => 'getTrafficClass',
        'workspace_id' => 'getWorkspaceId',
        'consent' => 'getConsent',
        'user_data_hashed' => 'getUserDataHashed',
        'click_ids' => 'getClickIds',
        'session' => 'getSession',
        'value_data' => 'getValueData',
        'event_source' => 'getEventSource',
        'payload_expired' => 'getPayloadExpired',
        'consent_source' => 'getConsentSource',
        'consent_ui_version' => 'getConsentUiVersion',
        'deliveries' => 'getDeliveries'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CONSENT_SOURCE_EXPLICIT = 'explicit';
    public const CONSENT_SOURCE_TCF = 'tcf';
    public const CONSENT_SOURCE_CONSENT_MODE = 'consent_mode';
    public const CONSENT_SOURCE_PLAINROUTER = 'plainrouter';
    public const CONSENT_SOURCE_CMP_COOKIEBOT = 'cmp:cookiebot';
    public const CONSENT_SOURCE_CMP_USERCENTRICS = 'cmp:usercentrics';
    public const CONSENT_SOURCE_CMP_COOKIEYES = 'cmp:cookieyes';
    public const CONSENT_SOURCE_CMP_CONSENTSTACK = 'cmp:consentstack';
    public const CONSENT_SOURCE_CMP_IUBENDA = 'cmp:iubenda';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getConsentSourceAllowableValues()
    {
        return [
            self::CONSENT_SOURCE_EXPLICIT,
            self::CONSENT_SOURCE_TCF,
            self::CONSENT_SOURCE_CONSENT_MODE,
            self::CONSENT_SOURCE_PLAINROUTER,
            self::CONSENT_SOURCE_CMP_COOKIEBOT,
            self::CONSENT_SOURCE_CMP_USERCENTRICS,
            self::CONSENT_SOURCE_CMP_COOKIEYES,
            self::CONSENT_SOURCE_CMP_CONSENTSTACK,
            self::CONSENT_SOURCE_CMP_IUBENDA,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('parent_event_id', $data ?? [], null);
        $this->setIfExists('event_name', $data ?? [], null);
        $this->setIfExists('event_time', $data ?? [], null);
        $this->setIfExists('action_source', $data ?? [], null);
        $this->setIfExists('event_class', $data ?? [], null);
        $this->setIfExists('order_id', $data ?? [], null);
        $this->setIfExists('value_amount', $data ?? [], null);
        $this->setIfExists('value_currency', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('consent_basis', $data ?? [], null);
        $this->setIfExists('measurement_class', $data ?? [], null);
        $this->setIfExists('attribution_join', $data ?? [], null);
        $this->setIfExists('enforcement_scope', $data ?? [], null);
        $this->setIfExists('consent_normalization_version', $data ?? [], null);
        $this->setIfExists('policy_class', $data ?? [], null);
        $this->setIfExists('traffic_class', $data ?? [], null);
        $this->setIfExists('workspace_id', $data ?? [], null);
        $this->setIfExists('consent', $data ?? [], null);
        $this->setIfExists('user_data_hashed', $data ?? [], null);
        $this->setIfExists('click_ids', $data ?? [], null);
        $this->setIfExists('session', $data ?? [], null);
        $this->setIfExists('value_data', $data ?? [], null);
        $this->setIfExists('event_source', $data ?? [], null);
        $this->setIfExists('payload_expired', $data ?? [], null);
        $this->setIfExists('consent_source', $data ?? [], null);
        $this->setIfExists('consent_ui_version', $data ?? [], null);
        $this->setIfExists('deliveries', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['parent_event_id'] === null && !$this->isNullableSetToNull('parent_event_id')) {
            $invalidProperties[] = "'parent_event_id' is required";
        }
        if ($this->container['event_name'] === null) {
            $invalidProperties[] = "'event_name' can't be null";
        }
        if ($this->container['event_time'] === null) {
            $invalidProperties[] = "'event_time' can't be null";
        }
        if ($this->container['action_source'] === null) {
            $invalidProperties[] = "'action_source' can't be null";
        }
        if ($this->container['event_class'] === null) {
            $invalidProperties[] = "'event_class' can't be null";
        }
        if ($this->container['order_id'] === null && !$this->isNullableSetToNull('order_id')) {
            $invalidProperties[] = "'order_id' is required";
        }
        if ($this->container['value_amount'] === null && !$this->isNullableSetToNull('value_amount')) {
            $invalidProperties[] = "'value_amount' is required";
        }
        if ($this->container['value_currency'] === null && !$this->isNullableSetToNull('value_currency')) {
            $invalidProperties[] = "'value_currency' is required";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['consent_basis'] === null) {
            $invalidProperties[] = "'consent_basis' can't be null";
        }
        if ($this->container['measurement_class'] === null) {
            $invalidProperties[] = "'measurement_class' can't be null";
        }
        if ($this->container['attribution_join'] === null) {
            $invalidProperties[] = "'attribution_join' can't be null";
        }
        if ($this->container['enforcement_scope'] === null) {
            $invalidProperties[] = "'enforcement_scope' can't be null";
        }
        if ($this->container['consent_normalization_version'] === null) {
            $invalidProperties[] = "'consent_normalization_version' can't be null";
        }
        if ($this->container['policy_class'] === null) {
            $invalidProperties[] = "'policy_class' can't be null";
        }
        if ($this->container['traffic_class'] === null) {
            $invalidProperties[] = "'traffic_class' can't be null";
        }
        if ($this->container['workspace_id'] === null) {
            $invalidProperties[] = "'workspace_id' can't be null";
        }
        if ($this->container['consent'] === null) {
            $invalidProperties[] = "'consent' can't be null";
        }
        if ($this->container['user_data_hashed'] === null && !$this->isNullableSetToNull('user_data_hashed')) {
            $invalidProperties[] = "'user_data_hashed' is required";
        }
        if ($this->container['click_ids'] === null) {
            $invalidProperties[] = "'click_ids' can't be null";
        }
        if ($this->container['session'] === null) {
            $invalidProperties[] = "'session' can't be null";
        }
        if ($this->container['value_data'] === null) {
            $invalidProperties[] = "'value_data' can't be null";
        }
        if ($this->container['event_source'] === null) {
            $invalidProperties[] = "'event_source' can't be null";
        }
        if ($this->container['payload_expired'] === null) {
            $invalidProperties[] = "'payload_expired' can't be null";
        }
        $allowedValues = $this->getConsentSourceAllowableValues();
        if (!is_null($this->container['consent_source']) && !in_array($this->container['consent_source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'consent_source', must be one of '%s'",
                $this->container['consent_source'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['consent_ui_version']) && ($this->container['consent_ui_version'] > 999999)) {
            $invalidProperties[] = "invalid value for 'consent_ui_version', must be smaller than or equal to 999999.";
        }

        if (!is_null($this->container['consent_ui_version']) && ($this->container['consent_ui_version'] < 1)) {
            $invalidProperties[] = "invalid value for 'consent_ui_version', must be bigger than or equal to 1.";
        }

        if ($this->container['deliveries'] === null) {
            $invalidProperties[] = "'deliveries' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets parent_event_id
     *
     * @return string|null
     */
    public function getParentEventId()
    {
        return $this->container['parent_event_id'];
    }

    /**
     * Sets parent_event_id
     *
     * @param string|null $parent_event_id parent_event_id
     *
     * @return self
     */
    public function setParentEventId($parent_event_id)
    {
        if (is_null($parent_event_id)) {
            array_push($this->openAPINullablesSetToNull, 'parent_event_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parent_event_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['parent_event_id'] = $parent_event_id;

        return $this;
    }

    /**
     * Gets event_name
     *
     * @return string
     */
    public function getEventName()
    {
        return $this->container['event_name'];
    }

    /**
     * Sets event_name
     *
     * @param string $event_name event_name
     *
     * @return self
     */
    public function setEventName($event_name)
    {
        if (is_null($event_name)) {
            throw new \InvalidArgumentException('non-nullable event_name cannot be null');
        }
        $this->container['event_name'] = $event_name;

        return $this;
    }

    /**
     * Gets event_time
     *
     * @return \DateTime
     */
    public function getEventTime()
    {
        return $this->container['event_time'];
    }

    /**
     * Sets event_time
     *
     * @param \DateTime $event_time event_time
     *
     * @return self
     */
    public function setEventTime($event_time)
    {
        if (is_null($event_time)) {
            throw new \InvalidArgumentException('non-nullable event_time cannot be null');
        }
        $this->container['event_time'] = $event_time;

        return $this;
    }

    /**
     * Gets action_source
     *
     * @return string
     */
    public function getActionSource()
    {
        return $this->container['action_source'];
    }

    /**
     * Sets action_source
     *
     * @param string $action_source action_source
     *
     * @return self
     */
    public function setActionSource($action_source)
    {
        if (is_null($action_source)) {
            throw new \InvalidArgumentException('non-nullable action_source cannot be null');
        }
        $this->container['action_source'] = $action_source;

        return $this;
    }

    /**
     * Gets event_class
     *
     * @return string
     */
    public function getEventClass()
    {
        return $this->container['event_class'];
    }

    /**
     * Sets event_class
     *
     * @param string $event_class event_class
     *
     * @return self
     */
    public function setEventClass($event_class)
    {
        if (is_null($event_class)) {
            throw new \InvalidArgumentException('non-nullable event_class cannot be null');
        }
        $this->container['event_class'] = $event_class;

        return $this;
    }

    /**
     * Gets order_id
     *
     * @return string|null
     */
    public function getOrderId()
    {
        return $this->container['order_id'];
    }

    /**
     * Sets order_id
     *
     * @param string|null $order_id order_id
     *
     * @return self
     */
    public function setOrderId($order_id)
    {
        if (is_null($order_id)) {
            array_push($this->openAPINullablesSetToNull, 'order_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['order_id'] = $order_id;

        return $this;
    }

    /**
     * Gets value_amount
     *
     * @return int|null
     */
    public function getValueAmount()
    {
        return $this->container['value_amount'];
    }

    /**
     * Sets value_amount
     *
     * @param int|null $value_amount value_amount
     *
     * @return self
     */
    public function setValueAmount($value_amount)
    {
        if (is_null($value_amount)) {
            array_push($this->openAPINullablesSetToNull, 'value_amount');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('value_amount', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['value_amount'] = $value_amount;

        return $this;
    }

    /**
     * Gets value_currency
     *
     * @return string|null
     */
    public function getValueCurrency()
    {
        return $this->container['value_currency'];
    }

    /**
     * Sets value_currency
     *
     * @param string|null $value_currency value_currency
     *
     * @return self
     */
    public function setValueCurrency($value_currency)
    {
        if (is_null($value_currency)) {
            array_push($this->openAPINullablesSetToNull, 'value_currency');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('value_currency', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['value_currency'] = $value_currency;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets consent_basis
     *
     * @return string
     */
    public function getConsentBasis()
    {
        return $this->container['consent_basis'];
    }

    /**
     * Sets consent_basis
     *
     * @param string $consent_basis consent_basis
     *
     * @return self
     */
    public function setConsentBasis($consent_basis)
    {
        if (is_null($consent_basis)) {
            throw new \InvalidArgumentException('non-nullable consent_basis cannot be null');
        }
        $this->container['consent_basis'] = $consent_basis;

        return $this;
    }

    /**
     * Gets measurement_class
     *
     * @return string
     */
    public function getMeasurementClass()
    {
        return $this->container['measurement_class'];
    }

    /**
     * Sets measurement_class
     *
     * @param string $measurement_class measurement_class
     *
     * @return self
     */
    public function setMeasurementClass($measurement_class)
    {
        if (is_null($measurement_class)) {
            throw new \InvalidArgumentException('non-nullable measurement_class cannot be null');
        }
        $this->container['measurement_class'] = $measurement_class;

        return $this;
    }

    /**
     * Gets attribution_join
     *
     * @return string
     */
    public function getAttributionJoin()
    {
        return $this->container['attribution_join'];
    }

    /**
     * Sets attribution_join
     *
     * @param string $attribution_join attribution_join
     *
     * @return self
     */
    public function setAttributionJoin($attribution_join)
    {
        if (is_null($attribution_join)) {
            throw new \InvalidArgumentException('non-nullable attribution_join cannot be null');
        }
        $this->container['attribution_join'] = $attribution_join;

        return $this;
    }

    /**
     * Gets enforcement_scope
     *
     * @return string
     */
    public function getEnforcementScope()
    {
        return $this->container['enforcement_scope'];
    }

    /**
     * Sets enforcement_scope
     *
     * @param string $enforcement_scope enforcement_scope
     *
     * @return self
     */
    public function setEnforcementScope($enforcement_scope)
    {
        if (is_null($enforcement_scope)) {
            throw new \InvalidArgumentException('non-nullable enforcement_scope cannot be null');
        }
        $this->container['enforcement_scope'] = $enforcement_scope;

        return $this;
    }

    /**
     * Gets consent_normalization_version
     *
     * @return string
     */
    public function getConsentNormalizationVersion()
    {
        return $this->container['consent_normalization_version'];
    }

    /**
     * Sets consent_normalization_version
     *
     * @param string $consent_normalization_version consent_normalization_version
     *
     * @return self
     */
    public function setConsentNormalizationVersion($consent_normalization_version)
    {
        if (is_null($consent_normalization_version)) {
            throw new \InvalidArgumentException('non-nullable consent_normalization_version cannot be null');
        }
        $this->container['consent_normalization_version'] = $consent_normalization_version;

        return $this;
    }

    /**
     * Gets policy_class
     *
     * @return \Plainrouter\OpenAPI\Model\JurisdictionPolicyClass
     */
    public function getPolicyClass()
    {
        return $this->container['policy_class'];
    }

    /**
     * Sets policy_class
     *
     * @param \Plainrouter\OpenAPI\Model\JurisdictionPolicyClass $policy_class policy_class
     *
     * @return self
     */
    public function setPolicyClass($policy_class)
    {
        if (is_null($policy_class)) {
            throw new \InvalidArgumentException('non-nullable policy_class cannot be null');
        }
        $this->container['policy_class'] = $policy_class;

        return $this;
    }

    /**
     * Gets traffic_class
     *
     * @return \Plainrouter\OpenAPI\Model\TrafficClass
     */
    public function getTrafficClass()
    {
        return $this->container['traffic_class'];
    }

    /**
     * Sets traffic_class
     *
     * @param \Plainrouter\OpenAPI\Model\TrafficClass $traffic_class traffic_class
     *
     * @return self
     */
    public function setTrafficClass($traffic_class)
    {
        if (is_null($traffic_class)) {
            throw new \InvalidArgumentException('non-nullable traffic_class cannot be null');
        }
        $this->container['traffic_class'] = $traffic_class;

        return $this;
    }

    /**
     * Gets workspace_id
     *
     * @return int
     */
    public function getWorkspaceId()
    {
        return $this->container['workspace_id'];
    }

    /**
     * Sets workspace_id
     *
     * @param int $workspace_id workspace_id
     *
     * @return self
     */
    public function setWorkspaceId($workspace_id)
    {
        if (is_null($workspace_id)) {
            throw new \InvalidArgumentException('non-nullable workspace_id cannot be null');
        }
        $this->container['workspace_id'] = $workspace_id;

        return $this;
    }

    /**
     * Gets consent
     *
     * @return string
     */
    public function getConsent()
    {
        return $this->container['consent'];
    }

    /**
     * Sets consent
     *
     * @param string $consent consent
     *
     * @return self
     */
    public function setConsent($consent)
    {
        if (is_null($consent)) {
            throw new \InvalidArgumentException('non-nullable consent cannot be null');
        }
        $this->container['consent'] = $consent;

        return $this;
    }

    /**
     * Gets user_data_hashed
     *
     * @return \Plainrouter\OpenAPI\Model\GetEvent200ResponseEventUserDataHashed|null
     */
    public function getUserDataHashed()
    {
        return $this->container['user_data_hashed'];
    }

    /**
     * Sets user_data_hashed
     *
     * @param \Plainrouter\OpenAPI\Model\GetEvent200ResponseEventUserDataHashed|null $user_data_hashed user_data_hashed
     *
     * @return self
     */
    public function setUserDataHashed($user_data_hashed)
    {
        if (is_null($user_data_hashed)) {
            array_push($this->openAPINullablesSetToNull, 'user_data_hashed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_data_hashed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_data_hashed'] = $user_data_hashed;

        return $this;
    }

    /**
     * Gets click_ids
     *
     * @return string
     */
    public function getClickIds()
    {
        return $this->container['click_ids'];
    }

    /**
     * Sets click_ids
     *
     * @param string $click_ids click_ids
     *
     * @return self
     */
    public function setClickIds($click_ids)
    {
        if (is_null($click_ids)) {
            throw new \InvalidArgumentException('non-nullable click_ids cannot be null');
        }
        $this->container['click_ids'] = $click_ids;

        return $this;
    }

    /**
     * Gets session
     *
     * @return string
     */
    public function getSession()
    {
        return $this->container['session'];
    }

    /**
     * Sets session
     *
     * @param string $session session
     *
     * @return self
     */
    public function setSession($session)
    {
        if (is_null($session)) {
            throw new \InvalidArgumentException('non-nullable session cannot be null');
        }
        $this->container['session'] = $session;

        return $this;
    }

    /**
     * Gets value_data
     *
     * @return string
     */
    public function getValueData()
    {
        return $this->container['value_data'];
    }

    /**
     * Sets value_data
     *
     * @param string $value_data value_data
     *
     * @return self
     */
    public function setValueData($value_data)
    {
        if (is_null($value_data)) {
            throw new \InvalidArgumentException('non-nullable value_data cannot be null');
        }
        $this->container['value_data'] = $value_data;

        return $this;
    }

    /**
     * Gets event_source
     *
     * @return string
     */
    public function getEventSource()
    {
        return $this->container['event_source'];
    }

    /**
     * Sets event_source
     *
     * @param string $event_source event_source
     *
     * @return self
     */
    public function setEventSource($event_source)
    {
        if (is_null($event_source)) {
            throw new \InvalidArgumentException('non-nullable event_source cannot be null');
        }
        $this->container['event_source'] = $event_source;

        return $this;
    }

    /**
     * Gets payload_expired
     *
     * @return bool
     */
    public function getPayloadExpired()
    {
        return $this->container['payload_expired'];
    }

    /**
     * Sets payload_expired
     *
     * @param bool $payload_expired payload_expired
     *
     * @return self
     */
    public function setPayloadExpired($payload_expired)
    {
        if (is_null($payload_expired)) {
            throw new \InvalidArgumentException('non-nullable payload_expired cannot be null');
        }
        $this->container['payload_expired'] = $payload_expired;

        return $this;
    }

    /**
     * Gets consent_source
     *
     * @return string|null
     */
    public function getConsentSource()
    {
        return $this->container['consent_source'];
    }

    /**
     * Sets consent_source
     *
     * @param string|null $consent_source consent_source
     *
     * @return self
     */
    public function setConsentSource($consent_source)
    {
        if (is_null($consent_source)) {
            throw new \InvalidArgumentException('non-nullable consent_source cannot be null');
        }
        $allowedValues = $this->getConsentSourceAllowableValues();
        if (!in_array($consent_source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'consent_source', must be one of '%s'",
                    $consent_source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['consent_source'] = $consent_source;

        return $this;
    }

    /**
     * Gets consent_ui_version
     *
     * @return int|null
     */
    public function getConsentUiVersion()
    {
        return $this->container['consent_ui_version'];
    }

    /**
     * Sets consent_ui_version
     *
     * @param int|null $consent_ui_version consent_ui_version
     *
     * @return self
     */
    public function setConsentUiVersion($consent_ui_version)
    {
        if (is_null($consent_ui_version)) {
            throw new \InvalidArgumentException('non-nullable consent_ui_version cannot be null');
        }
        if (($consent_ui_version > 999999)) {
            throw new \InvalidArgumentException('invalid value for $consent_ui_version when calling Event., must be smaller than or equal to 999999.');
        }
        if (($consent_ui_version < 1)) {
            throw new \InvalidArgumentException('invalid value for $consent_ui_version when calling Event., must be bigger than or equal to 1.');
        }

        $this->container['consent_ui_version'] = $consent_ui_version;

        return $this;
    }

    /**
     * Gets deliveries
     *
     * @return mixed[]
     */
    public function getDeliveries()
    {
        return $this->container['deliveries'];
    }

    /**
     * Sets deliveries
     *
     * @param mixed[] $deliveries deliveries
     *
     * @return self
     */
    public function setDeliveries($deliveries)
    {
        if (is_null($deliveries)) {
            throw new \InvalidArgumentException('non-nullable deliveries cannot be null');
        }
        $this->container['deliveries'] = $deliveries;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


