<?php
/**
 * GetInventoryMetrics200ResponseMetricsInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;

use \ArrayAccess;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * GetInventoryMetrics200ResponseMetricsInner Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetInventoryMetrics200ResponseMetricsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'get_inventory_metrics_200_response_metrics_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'id' => 'int',
        'platform_ad_account_id' => 'int',
        'ad_external_id' => 'string',
        'campaign_external_id' => 'string',
        'adset_external_id' => 'string',
        'date' => 'string',
        'account_currency' => 'string',
        'spend' => 'string',
        'impressions' => 'int',
        'clicks' => 'int',
        'inline_link_clicks' => 'int',
        'actions' => '\Plainrouter\OpenAPI\Model\GetEvent200ResponseEventConsent',
        'action_values' => '\Plainrouter\OpenAPI\Model\GetEvent200ResponseEventConsent',
        'fetched_at' => 'string',
        'arrivals' => 'int',
        'creative_id' => 'string',
        'generator' => 'string',
        'generator_job' => 'string',
        'parent_creative' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'id' => null,
        'platform_ad_account_id' => null,
        'ad_external_id' => null,
        'campaign_external_id' => null,
        'adset_external_id' => null,
        'date' => null,
        'account_currency' => null,
        'spend' => null,
        'impressions' => null,
        'clicks' => null,
        'inline_link_clicks' => null,
        'actions' => null,
        'action_values' => null,
        'fetched_at' => null,
        'arrivals' => null,
        'creative_id' => null,
        'generator' => null,
        'generator_job' => null,
        'parent_creative' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'id' => false,
        'platform_ad_account_id' => false,
        'ad_external_id' => false,
        'campaign_external_id' => true,
        'adset_external_id' => true,
        'date' => false,
        'account_currency' => false,
        'spend' => false,
        'impressions' => false,
        'clicks' => false,
        'inline_link_clicks' => false,
        'actions' => true,
        'action_values' => true,
        'fetched_at' => true,
        'arrivals' => true,
        'creative_id' => true,
        'generator' => true,
        'generator_job' => true,
        'parent_creative' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'platform_ad_account_id' => 'platform_ad_account_id',
        'ad_external_id' => 'ad_external_id',
        'campaign_external_id' => 'campaign_external_id',
        'adset_external_id' => 'adset_external_id',
        'date' => 'date',
        'account_currency' => 'account_currency',
        'spend' => 'spend',
        'impressions' => 'impressions',
        'clicks' => 'clicks',
        'inline_link_clicks' => 'inline_link_clicks',
        'actions' => 'actions',
        'action_values' => 'action_values',
        'fetched_at' => 'fetched_at',
        'arrivals' => 'arrivals',
        'creative_id' => 'creative_id',
        'generator' => 'generator',
        'generator_job' => 'generator_job',
        'parent_creative' => 'parent_creative'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'platform_ad_account_id' => 'setPlatformAdAccountId',
        'ad_external_id' => 'setAdExternalId',
        'campaign_external_id' => 'setCampaignExternalId',
        'adset_external_id' => 'setAdsetExternalId',
        'date' => 'setDate',
        'account_currency' => 'setAccountCurrency',
        'spend' => 'setSpend',
        'impressions' => 'setImpressions',
        'clicks' => 'setClicks',
        'inline_link_clicks' => 'setInlineLinkClicks',
        'actions' => 'setActions',
        'action_values' => 'setActionValues',
        'fetched_at' => 'setFetchedAt',
        'arrivals' => 'setArrivals',
        'creative_id' => 'setCreativeId',
        'generator' => 'setGenerator',
        'generator_job' => 'setGeneratorJob',
        'parent_creative' => 'setParentCreative'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'platform_ad_account_id' => 'getPlatformAdAccountId',
        'ad_external_id' => 'getAdExternalId',
        'campaign_external_id' => 'getCampaignExternalId',
        'adset_external_id' => 'getAdsetExternalId',
        'date' => 'getDate',
        'account_currency' => 'getAccountCurrency',
        'spend' => 'getSpend',
        'impressions' => 'getImpressions',
        'clicks' => 'getClicks',
        'inline_link_clicks' => 'getInlineLinkClicks',
        'actions' => 'getActions',
        'action_values' => 'getActionValues',
        'fetched_at' => 'getFetchedAt',
        'arrivals' => 'getArrivals',
        'creative_id' => 'getCreativeId',
        'generator' => 'getGenerator',
        'generator_job' => 'getGeneratorJob',
        'parent_creative' => 'getParentCreative'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('platform_ad_account_id', $data ?? [], null);
        $this->setIfExists('ad_external_id', $data ?? [], null);
        $this->setIfExists('campaign_external_id', $data ?? [], null);
        $this->setIfExists('adset_external_id', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('account_currency', $data ?? [], null);
        $this->setIfExists('spend', $data ?? [], null);
        $this->setIfExists('impressions', $data ?? [], null);
        $this->setIfExists('clicks', $data ?? [], null);
        $this->setIfExists('inline_link_clicks', $data ?? [], null);
        $this->setIfExists('actions', $data ?? [], null);
        $this->setIfExists('action_values', $data ?? [], null);
        $this->setIfExists('fetched_at', $data ?? [], null);
        $this->setIfExists('arrivals', $data ?? [], null);
        $this->setIfExists('creative_id', $data ?? [], null);
        $this->setIfExists('generator', $data ?? [], null);
        $this->setIfExists('generator_job', $data ?? [], null);
        $this->setIfExists('parent_creative', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['platform_ad_account_id'] === null) {
            $invalidProperties[] = "'platform_ad_account_id' can't be null";
        }
        if ($this->container['ad_external_id'] === null) {
            $invalidProperties[] = "'ad_external_id' can't be null";
        }
        if ($this->container['campaign_external_id'] === null && !$this->isNullableSetToNull('campaign_external_id')) {
            $invalidProperties[] = "'campaign_external_id' is required";
        }
        if ($this->container['adset_external_id'] === null && !$this->isNullableSetToNull('adset_external_id')) {
            $invalidProperties[] = "'adset_external_id' is required";
        }
        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ($this->container['account_currency'] === null) {
            $invalidProperties[] = "'account_currency' can't be null";
        }
        if ($this->container['spend'] === null) {
            $invalidProperties[] = "'spend' can't be null";
        }
        if ($this->container['impressions'] === null) {
            $invalidProperties[] = "'impressions' can't be null";
        }
        if ($this->container['clicks'] === null) {
            $invalidProperties[] = "'clicks' can't be null";
        }
        if ($this->container['inline_link_clicks'] === null) {
            $invalidProperties[] = "'inline_link_clicks' can't be null";
        }
        if ($this->container['actions'] === null && !$this->isNullableSetToNull('actions')) {
            $invalidProperties[] = "'actions' is required";
        }
        if ($this->container['action_values'] === null && !$this->isNullableSetToNull('action_values')) {
            $invalidProperties[] = "'action_values' is required";
        }
        if ($this->container['fetched_at'] === null && !$this->isNullableSetToNull('fetched_at')) {
            $invalidProperties[] = "'fetched_at' is required";
        }
        if ($this->container['arrivals'] === null && !$this->isNullableSetToNull('arrivals')) {
            $invalidProperties[] = "'arrivals' is required";
        }
        if ($this->container['creative_id'] === null && !$this->isNullableSetToNull('creative_id')) {
            $invalidProperties[] = "'creative_id' is required";
        }
        if ($this->container['generator'] === null && !$this->isNullableSetToNull('generator')) {
            $invalidProperties[] = "'generator' is required";
        }
        if ($this->container['generator_job'] === null && !$this->isNullableSetToNull('generator_job')) {
            $invalidProperties[] = "'generator_job' is required";
        }
        if ($this->container['parent_creative'] === null && !$this->isNullableSetToNull('parent_creative')) {
            $invalidProperties[] = "'parent_creative' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets platform_ad_account_id
     *
     * @return int
     */
    public function getPlatformAdAccountId()
    {
        return $this->container['platform_ad_account_id'];
    }

    /**
     * Sets platform_ad_account_id
     *
     * @param int $platform_ad_account_id platform_ad_account_id
     *
     * @return self
     */
    public function setPlatformAdAccountId($platform_ad_account_id)
    {
        if (is_null($platform_ad_account_id)) {
            throw new \InvalidArgumentException('non-nullable platform_ad_account_id cannot be null');
        }
        $this->container['platform_ad_account_id'] = $platform_ad_account_id;

        return $this;
    }

    /**
     * Gets ad_external_id
     *
     * @return string
     */
    public function getAdExternalId()
    {
        return $this->container['ad_external_id'];
    }

    /**
     * Sets ad_external_id
     *
     * @param string $ad_external_id ad_external_id
     *
     * @return self
     */
    public function setAdExternalId($ad_external_id)
    {
        if (is_null($ad_external_id)) {
            throw new \InvalidArgumentException('non-nullable ad_external_id cannot be null');
        }
        $this->container['ad_external_id'] = $ad_external_id;

        return $this;
    }

    /**
     * Gets campaign_external_id
     *
     * @return string|null
     */
    public function getCampaignExternalId()
    {
        return $this->container['campaign_external_id'];
    }

    /**
     * Sets campaign_external_id
     *
     * @param string|null $campaign_external_id campaign_external_id
     *
     * @return self
     */
    public function setCampaignExternalId($campaign_external_id)
    {
        if (is_null($campaign_external_id)) {
            array_push($this->openAPINullablesSetToNull, 'campaign_external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campaign_external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['campaign_external_id'] = $campaign_external_id;

        return $this;
    }

    /**
     * Gets adset_external_id
     *
     * @return string|null
     */
    public function getAdsetExternalId()
    {
        return $this->container['adset_external_id'];
    }

    /**
     * Sets adset_external_id
     *
     * @param string|null $adset_external_id adset_external_id
     *
     * @return self
     */
    public function setAdsetExternalId($adset_external_id)
    {
        if (is_null($adset_external_id)) {
            array_push($this->openAPINullablesSetToNull, 'adset_external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('adset_external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['adset_external_id'] = $adset_external_id;

        return $this;
    }

    /**
     * Gets date
     *
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string $date date
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets account_currency
     *
     * @return string
     */
    public function getAccountCurrency()
    {
        return $this->container['account_currency'];
    }

    /**
     * Sets account_currency
     *
     * @param string $account_currency account_currency
     *
     * @return self
     */
    public function setAccountCurrency($account_currency)
    {
        if (is_null($account_currency)) {
            throw new \InvalidArgumentException('non-nullable account_currency cannot be null');
        }
        $this->container['account_currency'] = $account_currency;

        return $this;
    }

    /**
     * Gets spend
     *
     * @return string
     */
    public function getSpend()
    {
        return $this->container['spend'];
    }

    /**
     * Sets spend
     *
     * @param string $spend spend
     *
     * @return self
     */
    public function setSpend($spend)
    {
        if (is_null($spend)) {
            throw new \InvalidArgumentException('non-nullable spend cannot be null');
        }
        $this->container['spend'] = $spend;

        return $this;
    }

    /**
     * Gets impressions
     *
     * @return int
     */
    public function getImpressions()
    {
        return $this->container['impressions'];
    }

    /**
     * Sets impressions
     *
     * @param int $impressions impressions
     *
     * @return self
     */
    public function setImpressions($impressions)
    {
        if (is_null($impressions)) {
            throw new \InvalidArgumentException('non-nullable impressions cannot be null');
        }
        $this->container['impressions'] = $impressions;

        return $this;
    }

    /**
     * Gets clicks
     *
     * @return int
     */
    public function getClicks()
    {
        return $this->container['clicks'];
    }

    /**
     * Sets clicks
     *
     * @param int $clicks clicks
     *
     * @return self
     */
    public function setClicks($clicks)
    {
        if (is_null($clicks)) {
            throw new \InvalidArgumentException('non-nullable clicks cannot be null');
        }
        $this->container['clicks'] = $clicks;

        return $this;
    }

    /**
     * Gets inline_link_clicks
     *
     * @return int
     */
    public function getInlineLinkClicks()
    {
        return $this->container['inline_link_clicks'];
    }

    /**
     * Sets inline_link_clicks
     *
     * @param int $inline_link_clicks inline_link_clicks
     *
     * @return self
     */
    public function setInlineLinkClicks($inline_link_clicks)
    {
        if (is_null($inline_link_clicks)) {
            throw new \InvalidArgumentException('non-nullable inline_link_clicks cannot be null');
        }
        $this->container['inline_link_clicks'] = $inline_link_clicks;

        return $this;
    }

    /**
     * Gets actions
     *
     * @return \Plainrouter\OpenAPI\Model\GetEvent200ResponseEventConsent|null
     */
    public function getActions()
    {
        return $this->container['actions'];
    }

    /**
     * Sets actions
     *
     * @param \Plainrouter\OpenAPI\Model\GetEvent200ResponseEventConsent|null $actions actions
     *
     * @return self
     */
    public function setActions($actions)
    {
        if (is_null($actions)) {
            array_push($this->openAPINullablesSetToNull, 'actions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('actions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['actions'] = $actions;

        return $this;
    }

    /**
     * Gets action_values
     *
     * @return \Plainrouter\OpenAPI\Model\GetEvent200ResponseEventConsent|null
     */
    public function getActionValues()
    {
        return $this->container['action_values'];
    }

    /**
     * Sets action_values
     *
     * @param \Plainrouter\OpenAPI\Model\GetEvent200ResponseEventConsent|null $action_values action_values
     *
     * @return self
     */
    public function setActionValues($action_values)
    {
        if (is_null($action_values)) {
            array_push($this->openAPINullablesSetToNull, 'action_values');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('action_values', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['action_values'] = $action_values;

        return $this;
    }

    /**
     * Gets fetched_at
     *
     * @return string|null
     */
    public function getFetchedAt()
    {
        return $this->container['fetched_at'];
    }

    /**
     * Sets fetched_at
     *
     * @param string|null $fetched_at fetched_at
     *
     * @return self
     */
    public function setFetchedAt($fetched_at)
    {
        if (is_null($fetched_at)) {
            array_push($this->openAPINullablesSetToNull, 'fetched_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fetched_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fetched_at'] = $fetched_at;

        return $this;
    }

    /**
     * Gets arrivals
     *
     * @return int|null
     */
    public function getArrivals()
    {
        return $this->container['arrivals'];
    }

    /**
     * Sets arrivals
     *
     * @param int|null $arrivals arrivals
     *
     * @return self
     */
    public function setArrivals($arrivals)
    {
        if (is_null($arrivals)) {
            array_push($this->openAPINullablesSetToNull, 'arrivals');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('arrivals', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['arrivals'] = $arrivals;

        return $this;
    }

    /**
     * Gets creative_id
     *
     * @return string|null
     */
    public function getCreativeId()
    {
        return $this->container['creative_id'];
    }

    /**
     * Sets creative_id
     *
     * @param string|null $creative_id creative_id
     *
     * @return self
     */
    public function setCreativeId($creative_id)
    {
        if (is_null($creative_id)) {
            array_push($this->openAPINullablesSetToNull, 'creative_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('creative_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['creative_id'] = $creative_id;

        return $this;
    }

    /**
     * Gets generator
     *
     * @return string|null
     */
    public function getGenerator()
    {
        return $this->container['generator'];
    }

    /**
     * Sets generator
     *
     * @param string|null $generator generator
     *
     * @return self
     */
    public function setGenerator($generator)
    {
        if (is_null($generator)) {
            array_push($this->openAPINullablesSetToNull, 'generator');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('generator', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['generator'] = $generator;

        return $this;
    }

    /**
     * Gets generator_job
     *
     * @return string|null
     */
    public function getGeneratorJob()
    {
        return $this->container['generator_job'];
    }

    /**
     * Sets generator_job
     *
     * @param string|null $generator_job generator_job
     *
     * @return self
     */
    public function setGeneratorJob($generator_job)
    {
        if (is_null($generator_job)) {
            array_push($this->openAPINullablesSetToNull, 'generator_job');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('generator_job', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['generator_job'] = $generator_job;

        return $this;
    }

    /**
     * Gets parent_creative
     *
     * @return string|null
     */
    public function getParentCreative()
    {
        return $this->container['parent_creative'];
    }

    /**
     * Sets parent_creative
     *
     * @param string|null $parent_creative parent_creative
     *
     * @return self
     */
    public function setParentCreative($parent_creative)
    {
        if (is_null($parent_creative)) {
            array_push($this->openAPINullablesSetToNull, 'parent_creative');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parent_creative', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['parent_creative'] = $parent_creative;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


