<?php
/**
 * LaunchIntentStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Plainrouter Conversion API
 *
 * Plainrouter public Signals Conversion API.
 *
 * The version of the OpenAPI document: 0.5.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Plainrouter\OpenAPI\Model;
use \Plainrouter\OpenAPI\ObjectSerializer;

/**
 * LaunchIntentStatus Class Doc Comment
 *
 * @category Class
 * @package  Plainrouter\OpenAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LaunchIntentStatus
{
    /**
     * Possible values of this enum
     */
    public const APPROVAL_REQUIRED = 'approval_required';

    public const APPROVED = 'approved';

    public const EXECUTING = 'executing';

    public const VERIFIED = 'verified';

    public const FAILED = 'failed';

    public const DRIFTED = 'drifted';

    public const PARTIAL = 'partial';

    public const BLOCKED = 'blocked';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::APPROVAL_REQUIRED,
            self::APPROVED,
            self::EXECUTING,
            self::VERIFIED,
            self::FAILED,
            self::DRIFTED,
            self::PARTIAL,
            self::BLOCKED
        ];
    }
}


